//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrizeBondStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrizeBond
    {
        public string PrizeBondCode { get; set; }
        public int DenominationId { get; set; }
    
        public virtual Denomination Denomination { get; set; }
    }
}
